name: Update Issues Table

on:
  issues:
    types: [opened, closed]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Update README
      run: node index.js
      env:
        OWNER: owner
        REPO: repo
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} 

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update README with latest issues"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
